- .github/workflows/tests.yml
- package.json
- yarn.lock
- добавлен action запуска тестов на MR'ах
- правки package.json
- удален jest-junit
> Запуск тестов, линтера и проверки типов в CI

- src/desktop/components/gallery-modal/components/image-overlay.module.scss
- GalleryModal: добавлена возможность сохранять фото через контекстное меню
> GalleryModal: Возможность сохранять фото через контекстное меню

- .github/workflows/npm-publish.yml
> Правки CI-конфига

- src/desktop/components/recommendation-carousel/__stories__/index.stories.jsx
- src/desktop/components/recommendation-carousel/__test__/__snapshots__/hover-card.test.tsx.snap
- src/desktop/components/recommendation-carousel/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/recommendation-carousel/__test__/__snapshots__/product-card.test.jsx.snap
- src/desktop/components/recommendation-carousel/__test__/__snapshots__/product-info.test.jsx.snap
- src/desktop/components/recommendation-carousel/__test__/hover-card.test.tsx
- src/desktop/components/recommendation-carousel/__test__/index.test.tsx
- src/desktop/components/recommendation-carousel/__test__/product-info.test.jsx
- src/desktop/components/recommendation-carousel/hover-card.tsx
- src/desktop/components/recommendation-carousel/index.tsx
- src/desktop/components/recommendation-carousel/product-card.tsx
- src/desktop/components/recommendation-carousel/product-info.tsx
- src/desktop/components/recommendation-carousel/types.ts
- ProductInfo: добавлена возможность обрабатывать клик по ссылкам на товар
- RecommendationCarousel: добавлена возможность обрабатывать клик по ссылкам на товар
Closes #19
> ProductInfo: Возможность обрабатывать клик по ссылкам на товар

- package.json
- yarn.lock
- обновлены пакеты @sima-land/ui-nucleons, @sima-land/ui-quarks
Closes #21
> Обновления пакетов @sima-land/ui-nucleons, @sima-land/ui-quarks

- src/desktop/components/promotion-card/index.module.scss
- PromotionCard: обновлены стили для правки бага в Safari
Проверено:
<details>
<summary>GIF</summary>
</details>
Closes #25
> #25 PromotionCard: Исправление бага Safari

- src/desktop/components/promotion-card/__test__/__snapshots__/estimate.test.tsx.snap
- src/desktop/components/promotion-card/estimate.tsx
- правки вывода оставшегося времени
Closes #27
> #27 Правки вывода оставшегося времени

- package.json
- src/desktop/components/person-modal/__test__/__snapshots__/index.test.jsx.snap
- src/desktop/components/person-modal/index.tsx
- src/mobile/components/person-screen/__test__/__snapshots__/index.test.js.snap
- src/mobile/components/person-screen/index.tsx
- src/mobile/components/product-card/__test__/__snapshots__/index.test.js.snap
- src/mobile/components/product-card/index.tsx
- yarn.lock
- обновлен пакет `@sima-land/ui-nucleons`
- исправлено использование `<Text />`
- обновлены snapshot'ы
Closes #33
> Обновление нуклонов

- src/desktop/components/promotion-card/__test__/__snapshots__/estimate.test.tsx.snap
- src/desktop/components/promotion-card/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/promotion-card/__test__/estimate.test.tsx
- src/desktop/components/promotion-card/estimate.tsx
- PromotionCard: упрощен вывод оставшегося времени согласно обновленным дизайн-гайдам
Closes #35
> #35 PromotionCard: обновления вывода оставшегося времени

- src/desktop/components/product-card/product-card.module.scss
- ProductCard: добавлен cursor:pointer при наведении на кнопку быстрого просмотра
Closes #39
> ProductCard: добавлен cursor:pointer

- src/common/components/product-info/__stories__/index.stories.tsx
- src/common/components/product-info/__test__/__snapshots__/index.test.tsx.snap
- src/common/components/product-info/__test__/index.test.tsx
- src/common/components/product-info/index.tsx
- src/common/components/product-info/product-info.module.scss
- src/desktop/components/product-card/__stories__/index.stories.tsx
- src/desktop/components/product-carousel/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/product-carousel/__test__/test-items.ts
- `ProductInfo`: добавлена возможность выводить ссылку на торговую марку
- добавлены тесты
- дополнены stories
Closes #53
> #53 ProductInfo: добавлена возможность выводить ссылку на торговую марку

- src/desktop/components/product-carousel/__stories__/index.stories.tsx
- src/desktop/components/product-carousel/index.tsx
- `ProductCarousel`: в зависимости эффекта для расчета ширины элемента добавлено кол-во элементов
- добавлена story для визуальной проверки
Closes #55
> #55 ProductCarousel: неправильно определяется вертикальная позиция кнопок

- src/desktop/components/promotion-card/__test__/__snapshots__/banner-title.test.tsx.snap
- src/desktop/components/promotion-card/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/promotion-card/__test__/index.test.tsx
- src/desktop/components/promotion-card/banner-title.tsx
- src/desktop/components/promotion-card/index.tsx
- src/desktop/components/promotion-card/placeholder.tsx
- `PromotionCard`: добавлены атрибуты `data-testid`
- обновлены тесты
Closes #60
> #60 PromotionCard: добавлены data-testid атрибуты

- src/desktop/components/promotion-card/__test__/__snapshots__/estimate.test.tsx.snap
- src/desktop/components/promotion-card/__test__/estimate.test.tsx
- src/desktop/components/promotion-card/estimate.tsx
- `PromotionCard`: правки вывода месяца у даты
- добавлены тесты
Closes #62
> #62 PromotionCard: правки вывода месяца у даты

- src/mobile/components/select-screen/__stories__/index.stories.tsx
- src/mobile/components/select-screen/__test__/__snapshots__/index.test.jsx.snap
- src/mobile/components/select-screen/__test__/index.test.jsx
- src/mobile/components/select-screen/index.tsx
- src/mobile/components/select-screen/select-screen.module.scss
- `mobile/SelectScreen`: компонент помечен как deprecated (patch)
- `mobile/SelectScreen`: индексный файл теперь экспортирует SelectScreenLayout и SelectScreenOption (minor)
Closes #67
> #67  mobile/SelectScreen: пересмотреть компонент

- src/common/components/product-info/product-info.module.scss
- ProductInfo: правки стилей для сафари
Closes #75
> #75  ProductInfo: картинка не показывается в Safari 14

- src/desktop/components/modifiers/group/index.tsx
- правки интерфейса ModifiersGroupProps (отсутствовал проп needShowAll)
- мелкие правки JSDoc
Closes #79
> #79 ModifiersGroup: исправить отсутствие пропа needShowAll в интерфейсе пропсов

- src/mobile/components/select-screen/__stories__/index.stories.tsx
- src/mobile/components/select-screen/__test__/__snapshots__/index.test.jsx.snap
- src/mobile/components/select-screen/__test__/index.test.jsx
- src/mobile/components/select-screen/index.tsx
- src/mobile/components/select-screen/select-screen.module.scss
- `SelectScreenOption`: добавлена возможность задавать размер по гайдам
- `SelectScreenOption`: добавлена возможность отключать иконку галочки
- `SelectScreenOption`: правки стилей для состояния disabled
Closes #77
> #77  SelectScreen: доработать компонент опции

- src/desktop/components/product-carousel/__test__/index.test.tsx
- src/desktop/components/product-carousel/index.tsx
- ProductCarousel: добавлена проверка наличия данных для показа всплывающей карточки
- добавлены unit-тесты
Closes #85
> #85  ProductCarousel: исправить ошибку при удалении контента при показанной всплывающей карточке

- package-lock.json
- package.json
- src/common/components/product-info/product-info.module.scss
- src/mobile/components/modifiers-list/__stories__/index.stories.jsx
- src/mobile/components/product-slider/__stories__/index.stories.tsx
- src/mobile/components/product-slider/__test__/__snapshots__/index.test.tsx.snap
- обновлен пакет `@sima-land/ui-nucleons`
- `ProductInfo`: правки вывода изображения (не растягивалось на всю ширину/высоту)
- `ModifiersList`: мелкие правки stories
- `ProductSlider`: мелкие правки stories
Fix #82
> #82 Обновить @sima-land/ui-nucleons до версии 43

- src/mobile/components/search-bar/__test__/index.test.jsx
- src/mobile/components/search-bar/index.tsx
- `SearchBar`: добавлен проброс рефа для текстового поля (minor)
- `SearchBar`: мелкие правки JSDoc (patch)
- `SearchBar`: добавлены тесты (patch)
Closes #101
> #101  SearchBar: добавить проброс ref для текстового поля

- src/mobile/components/search-bar/search-bar.module.scss
- SearchBar: правки стилей описания в поле (patch)
Closes #106
> #106 SearchBar: исправить отступ описания в поле

- .eslintrc.js
- src/desktop/components/gallery-modal/__stories__/index.stories.tsx
- src/desktop/components/gallery-modal/__test__/utils.test.tsx
- src/desktop/components/gallery-modal/components/__test__/__snapshots__/gallery-modal.test.tsx.snap
- src/desktop/components/gallery-modal/components/__test__/__snapshots__/review-info.test.tsx.snap
- src/desktop/components/gallery-modal/components/__test__/gallery-modal.test.tsx
- src/desktop/components/gallery-modal/components/__test__/review-info.test.tsx
- src/desktop/components/gallery-modal/components/gallery-modal.module.scss
- src/desktop/components/gallery-modal/components/gallery-modal.tsx
- src/desktop/components/gallery-modal/components/review-info.module.scss
- src/desktop/components/gallery-modal/components/review-info.tsx
- src/desktop/components/gallery-modal/utils.ts
- GalleryModal: доработан вывод отзыва по новым гайдам
Closes #108
> #108  Доработать компонент GalleryModal

- src/mobile/components/product-slider/__test__/__snapshots__/index.test.tsx.snap
- src/mobile/components/product-slider/__test__/index.test.tsx
- src/mobile/components/product-slider/index.tsx
- ProductSlider: добавлен data-testid для элементов слайдера
Closes #109
> #109  ProductSlider: добавить data-testid для элементов слайдера

- src/common/components/badge-list/__stories__/index.stories.tsx
- src/common/components/badge-list/__test__/__snapshots__/index.test.tsx.snap
- src/common/components/badge-list/__test__/index.test.tsx
- src/common/components/badge-list/badge-list.module.scss
- src/common/components/badge-list/index.tsx
- src/common/components/badge/__stories__/badge.stories.tsx
- src/common/components/badge/__test__/index.test.tsx
- src/common/components/badge/index.tsx
- src/common/components/product-info/__test__/__snapshots__/index.test.tsx.snap
- src/mobile/components/product-slider/__test__/__snapshots__/index.test.tsx.snap
- `Badge`: добавлен проброс ref 
- `BadgeList`: добавлена возможность явно оборачивать Badge другими компонентами
- добавлены примеры шильдиков с хинтами в Storybook
Closes #110
> #110 Добавить возможность выводить хинты для Badge

- src/desktop/components/gallery-modal/__stories__/index.stories.tsx
- src/desktop/components/gallery-modal/components/review-info.tsx
- GalleryModal: добавлен сброс состояния при изменении отзыва или автора
- обновлены stories
Closes #118
> #118  GalleryModal: поправить логику отображения кнопки 'показать полностью'/'скрыть отзыв'

- src/common/components/product-info/__stories__/index.stories.tsx
- src/common/components/product-info/__test__/__snapshots__/index.test.tsx.snap
- src/common/components/product-info/__test__/index.test.tsx
- src/common/components/product-info/index.tsx
- src/common/components/product-info/parts.tsx
- src/common/components/product-info/product-info.module.scss
- `ProductInfo`: добавлена возможность позиционировать кнопки-иконки на изображении (minor)
- `ProductInfo`: добавлена возможность задавать анправление тултипа кнопки-иконки (minor)
- `ProductInfo`: добавлена возможность выводить серый текст под названием товара по гайдам (minor)
Closes #117
> #117  ProductInfo: добавить возможность выводить кнопки-иконки на изображении в разных позициях

- src/common/components/badge-list/index.tsx
- src/common/components/badge/__test__/__snapshots__/index.test.tsx.snap
- src/common/components/badge/__test__/index.test.tsx
- src/common/components/badge/index.tsx
- src/desktop/components/breadcrumbs/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/breadcrumbs/__test__/index.test.tsx
- src/desktop/components/breadcrumbs/index.tsx
- src/mobile/components/breadcrumbs/__test__/__snapshots__/index.test.tsx.snap
- src/mobile/components/breadcrumbs/__test__/index.test.tsx
- src/mobile/components/breadcrumbs/index.tsx
- `common/Badge`: правки вывода img для SEO (patch)
- `desktop/Breadcrumbs`: правки вывода ссылок для SEO (patch)
- `mobile/Breadcrumbs`: правки вывода ссылок для SEO (patch)
Closes #121
> #121  Внести доработки в компоненты для SEO

- src/common/components/intractive-image/interactive-image.module.scss
- src/common/components/product-info/__stories__/index.stories.tsx
- src/common/components/product-info/types.ts
- src/desktop/components/product-card/__stories__/index.stories.tsx
- src/desktop/components/product-carousel/__stories__/index.stories.tsx
- interactive-image: обновлен размер точек на картинке
- мелкие доработки stories
- мелкие правки JSDoc
Closes #125
> #125 Поправить размер точек у InteractiveImage

- src/common/components/intractive-image/__stories__/index.stories.tsx
- src/common/components/intractive-image/__test__/index.test.tsx
- src/common/components/intractive-image/interactive-image.module.scss
- src/common/components/intractive-image/interactive-image.tsx
- interactive-image: добавлена возможность задавать ссылку фоном
Closes #130
> #130 InteractiveImage: Добавить возможность обернуть изображение в ссылку

- .github/actions/publish-notify/action.yml
- .github/workflows/npm-publish.yml
- добавлена временная реализация оповещений о публикации в tg
> #130 Оповещения в TG

- postcss.config.js
- src/common/components/badge-list/index.tsx
- src/common/components/intractive-image/interactive-image.tsx
- src/common/components/product-info/index.tsx
- src/custom.d.ts
- src/desktop/components/gallery-modal/components/all-round-view.tsx
- src/desktop/components/gallery-modal/components/gallery-modal.tsx
- src/desktop/components/gallery-modal/components/image-overlay.tsx
- src/desktop/components/gallery-modal/components/review-info.tsx
- src/desktop/components/gallery-modal/components/thumbnail.tsx
- src/desktop/components/gallery-modal/utils.ts
- src/desktop/components/modifiers/group/index.tsx
- src/desktop/components/product-card/index.tsx
- src/desktop/components/product-carousel/index.tsx
- src/desktop/components/promotion-card/banner-title.tsx
- src/desktop/components/promotion-card/estimate.tsx
- src/mobile/components/breadcrumbs/index.tsx
- src/mobile/components/search-bar/index.tsx
- tsconfig.json
- добавлен JSDoc
- удалены лишние конфиги
> Шаг 2 Обновить нуклоны до версии 45

- .jest/setup.js
- src/desktop/components/gallery-modal/components/__test__/__snapshots__/gallery-modal.test.tsx.snap
- src/desktop/components/product-carousel/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/product-carousel/__test__/utils.test.tsx
- src/desktop/components/product-carousel/index.tsx
- src/desktop/components/product-carousel/utils.ts
- ProductCarousel: поиск элемента по селектору заменен на ref
- ProductCarousel: useChildWidth заменен на useClientWidth
- добавлен mock для ResizeObserver в Jest
Closes #149
> #149 ProductCarousel: неправильно формируется селектор для поиска дочерних элементов

- src/desktop/components/modifiers/group/modifiers-group.module.scss
- ModifiersGroup: правки стилей скрытой кнопки показа всех модификаторов
Closes #152
> #152 Modifiers: невидимая кнопка имеет cursor: pointer

- src/common/components/modifiers/__stories__/index.stories.tsx
- src/common/components/modifiers/__test__/index.test.tsx
- src/common/components/modifiers/index.tsx
- src/common/components/modifiers/modifiers.module.scss
- common/modifier: добавлен компонент MoreButton
- common/modifier: добавлены сторисы с примерами использования
> Шаг 2 #150

- src/common/components/media-modal/__stories__/only-360.stories.tsx
- src/common/components/media-modal/__stories__/only-video.stories.tsx
- src/common/components/media-modal/index.tsx
- src/common/components/media-modal/layout.module.scss
- src/common/components/media-modal/layout.tsx
- src/common/components/media-modal/parts/media-content.module.scss
- src/common/components/media-modal/parts/media-content.tsx
- src/common/components/media-modal/parts/media-view.module.scss
- src/common/components/media-modal/parts/media-view.tsx
- src/common/components/media-modal/utils.ts
- media-modal: доработки для вывода только видео и только 360
> Шаг 3 #157

- src/common/components/media-modal/__stories__/product.stories.tsx
- src/common/components/media-modal/__stories__/review.stories.tsx
- src/common/components/media-modal/layout.module.scss
- src/common/components/media-modal/parts/media-content.tsx
- src/common/components/media-modal/parts/media-view.tsx
- src/common/components/media-modal/parts/scroll-section.tsx
- src/common/components/media-modal/parts/thumbnails.tsx
- src/common/components/media-modal/utils.ts
- src/desktop/components/gallery-modal/components/all-round-view.tsx
- media-modal: добавлена прокрутка превью
- media-modal: на мобилках у 360 скрываются кнопки
- media-modal: правки расчета размера размера медиа контента
> Шаг 4 #157

- src/common/components/media-modal/__stories__/areas.stories.tsx
- src/common/components/media-modal/__stories__/review.stories.tsx
- src/common/components/media-modal/index.tsx
- src/common/components/media-modal/parts/media-content.module.scss
- src/common/components/media-modal/parts/media-content.tsx
- src/common/components/media-modal/parts/media-view.module.scss
- src/common/components/media-modal/parts/scroll-section.module.scss
- src/common/components/media-modal/parts/scroll-section.tsx
- src/common/components/media-modal/utils.ts
- src/desktop/components/gallery-modal/components/all-round-view.tsx
- правки для iOS Safari 14 (небыло отступов по лейауту у прокручиваемых секций)
- desktop/gallery-modal: правки расчетов
> Шаг 5 #157

- src/common/components/modifier/__stories__/index.stories.tsx
- src/common/components/rating-counter/rating-counter-util.scss
- modifier: доработки сторисов
- rating-counter: правки стилей
> Шаг 1 #170 Внести доработки в компоненты на основе изменений в гайдах

- src/common/components/media-modal/__stories__/loading-mixed.stories.tsx
- src/common/components/media-modal/__stories__/many-videos.stories.tsx
- src/common/components/media-modal/__stories__/product.stories.tsx
- src/common/components/media-modal/__stories__/review.stories.tsx
- src/common/components/media-modal/parts/media-content.tsx
- media-modal: добавлена возможность прокидывать videoProps элементам списка в MediaContent
> Шаг 3 #170 Внести доработки в компоненты на основе изменений в гайдах

- src/common/components/media-modal/__mocks__/index.ts
- src/common/components/media-modal/__stories__/test-images-broken.stories.tsx
- src/common/components/media-modal/parts/media-content.tsx
- src/common/components/media-modal/parts/media-view.module.scss
- src/common/components/media-modal/parts/media-view.tsx
- src/common/components/media-modal/parts/product-brief.module.scss
- src/common/components/media-modal/parts/product-brief.tsx
- src/common/components/media-modal/parts/thumbnail.module.scss
- src/common/components/media-modal/parts/thumbnail.tsx
- src/common/components/modifier/index.tsx
- src/common/hooks/index.ts
- добавлен хук управления состоянием ошибки загрузки картинки
- media-modal: добавлены заглушки для превью фото/видео, выбранного фото, фото товара в футере
> Шаг 4 #170 Внести доработки в компоненты на основе изменений в гайдах

- src/desktop/components/gallery-modal/__test__/utils.test.tsx
- src/desktop/components/gallery-modal/components/__test__/all-round-view.test.tsx
- src/desktop/components/gallery-modal/components/all-round-view.module.scss
- src/desktop/components/gallery-modal/components/all-round-view.tsx
- src/desktop/components/gallery-modal/utils.ts
- gallery-modal: добавлена заглушка фото для 360
- gallery-modal: useImagesLoad теперь возвращает строку вместо boolean
> Шаг 5 #170 Внести доработки в компоненты на основе изменений в гайдах

- src/desktop/components/product-carousel/__stories__/index.stories.tsx
- src/desktop/components/product-carousel/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/product-carousel/__test__/index.test.tsx
- src/desktop/components/product-carousel/index.tsx
- ProductCarousel: добавлена возможность задавать className/style элементам карусели
- ProductCarousel: добавлена возможность сбросить размер элемента карусели по умолчанию передав `itemSize='unset'`
Closes #169
> Шаг 2 #169 ProductCarousel: добавить возможность задавать произвольный размер ячейки

- src/common/components/pagination-controls/__stories__/index.stories.tsx
- src/common/components/pagination-controls/pagination-controls.tsx
- src/common/components/pagination-controls/types.ts
- pagination-controls: добавлена возможность скрыть форму
Closes #178
> Шаг 3 #178 Реализовать компонент PaginationBlock

- src/common/components/pagination-controls/pagination-controls.module.scss
- src/common/components/pagination-controls/pagination-controls.tsx
- pagination-controls: изменен компонент по обновленным дизайн-гайдам
> Шаг 4 #178 Реализовать компонент PaginationBlock

- package-lock.json
- package.json
- src/common/components/modifier/__stories__/index.stories.tsx
- src/common/components/pagination-controls/__stories__/index.stories.tsx
- src/common/components/pagination-controls/pagination-controls.tsx
- обновлены нуклоны
- `pagination-controls`: задействована валидация из nucleons/pagination
- `modifier`: мелкие правки stories
Closes #178
> Шаг 5 #178 Реализовать компонент PaginationBlock

- src/common/components/media-modal/parts/product-brief.module.scss
- src/common/components/media-modal/parts/review.module.scss
- src/common/components/modifier/modifier.module.scss
- src/common/components/product-info/product-info.module.scss
- src/desktop/components/gallery-modal/components/review-info.module.scss
- src/desktop/components/modifiers/button/modifier-button.module.scss
- src/desktop/components/person-info/person-info.module.scss
- src/desktop/components/product-carousel/product-carousel.module.scss
- src/desktop/components/promotion-card/index.module.scss
- src/mobile/components/modifiers-list/modifier-item/modifier-item.module.scss
- src/mobile/components/modifiers-list/modifiers-list.module.scss
- src/mobile/components/person-info/person-info.module.scss
- src/mobile/components/search-bar/search-bar.module.scss
- правки стилей по соглашению (отказ от weight 500)
>  Шаг 3 #197 Перейти на React 18

- package-lock.json
- package.json
- src/common/components/modifier/types.ts
- src/desktop/components/person-info/__stories__/index.stories.tsx
- src/desktop/components/person-info/index.tsx
- src/desktop/components/product-carousel/utils.ts
- src/mobile/components/person-info/__stories__/index.stories.tsx
- src/mobile/components/person-info/__test__/index.test.tsx
- src/mobile/components/person-info/index.tsx
- src/mobile/components/person-info/person-info.module.scss
- обновлен реакт
- обновлены нуклоны
- обновлен testing-library
- обновлены компоненты, типы и интерфейсы после обновления `react` и `@sima-land/ui-nucleons`
> Шаг 6 #197 Перейти на React 18

- package-lock.json
- src/common/components/pagination-controls/__stories__/index.stories.tsx
- src/common/components/pagination-controls/index.ts
- src/common/components/pagination-controls/pagination-controls.module.scss
- src/common/components/pagination-controls/pagination-controls.tsx
- src/common/components/pagination-controls/types.ts
- pagination-controls: обновлен для соответствия исправлениям в дизайн-гайдах
Closes #196
> #196 PaginationBlock: Изменить в соответствии с исправленными дизайн-гайдами

- src/desktop/components/breadcrumbs/__test__/__snapshots__/index.test.tsx.snap
- src/desktop/components/breadcrumbs/breadcrumbs.module.scss
- src/desktop/components/breadcrumbs/index.tsx
- desktop/breadcrumbs: обновлены области взаимодействия
> Шаг 2 #208 Breadсrumbs: обновить компонент в соответствии с исправлениями дизайн-гайдах

- src/desktop/components/product-card/__stories__/01-primary.stories.tsx
- src/desktop/components/product-card/__test__/product-card.test.tsx
- src/desktop/components/product-card/product-card.tsx
- src/desktop/components/product-card/types.ts
- `product-card`: теперь можно задать функцию фильтрации кнопок на изображении как опцию `hideImageButtons` функции `reduceBaseInfo` (minor)
> Шаг 2 #213 ProductCard: добавить возможность определять фильтры содержимого

- .github/workflows/gh-pages.yml
- .github/workflows/npm-publish.yml
- .github/workflows/tests.yml
- ci: версия node поднята до 20
> Шаг 2 #218 Обновить ui-nucleons 

- .jest/babel.config.js
- .storybook/main.js
- babel.config.js
- jest.config.mjs
- package.json
- добавлен type commonjs явно в package.json
- конфиг babel для storybook перенесен в .storybook/main.js
- конфиг babel для jest перенесен в .jest/babel.config.js
>  Шаг 3 #228 Прибраться перед очередным релизом

- package-lock.json
- package.json
- обновлена peer-зависимость date-fns (major)
Closes #233
> #233 Обновить date-fns для совместимости с новыми нуклонами

- .storybook/utils.m.scss
- .storybook/utils.tsx
- src/common/components/badge-list/__test__/__snapshots__/badge-list.test.tsx.snap
- src/common/components/badge/__stories__/badge.stories.tsx
- src/common/components/badge/__test__/__snapshots__/badge.test.tsx.snap
- src/common/components/badge/__test__/badge.test.tsx
- src/common/components/badge/badge.module.scss
- src/common/components/badge/badge.tsx
- src/common/components/badge/index.ts
- src/common/components/badge/types.ts
- src/common/components/product-info/__test__/__snapshots__/product-info.test.tsx.snap
- src/custom.d.ts
- src/mobile/components/product-slider/__test__/__snapshots__/product-slider.test.tsx.snap
- tsconfig.json
- badge: добавлен проп shape - возможность задать скругления (minor)
- badge: добавлен проп coloring - возможность определить как будет применяться цвет (minor)
- badge: добавлен проп withHoverEffect для управления эффектом при наведении независимо от href (minor)
> #236 Badge: обновить в соответствии с новыми дизайн-гайдами #236 

- src/common/components/badge/__stories__/badge.stories.tsx
- src/common/components/badge/badge.module.scss
- src/common/components/badge/types.ts
- badge: доработки stories (patch)
> Шаг 2 #236 Badge: обновить в соответствии с новыми дизайн-гайдами #236

- package-lock.json
- src/common/components/media-modal/__stories__/01-areas.stories.tsx
- src/common/components/media-modal/__stories__/02-tabs.stories.tsx
- src/common/components/media-modal/__stories__/03-tabs-with-button.stories.tsx
- src/common/components/media-modal/__stories__/04-thumbnails.stories.tsx
- src/common/components/media-modal/__stories__/05-thumbnails-video.stories.tsx
- src/common/components/media-modal/__stories__/06-footer-product.stories.tsx
- src/common/components/media-modal/__stories__/07-footer-review.stories.tsx
- src/common/components/media-modal/__stories__/08-gallery.stories.tsx
- src/common/components/media-modal/__stories__/09-gallery-video.stories.tsx
- src/common/components/media-modal/__stories__/test-images-broken.stories.tsx
- src/common/components/media-modal/parts/product-brief.module.scss
- src/common/components/media-modal/parts/product-brief.tsx
- src/common/components/media-modal/parts/thumbnail.module.scss
- выполнен npm audit fix
- media-modal: обновления стилей из-за правок в гайдах (patch)
- media-modal: добавлена возможность выводить текст вместо цены в блоке товара в футере (minor)
> Шаг 1 #235 MediaLayout: обновить в соответствии с новыми дизайн-гайдами 

- src/common/components/media-modal/__stories__/07-footer-product-added.stories.tsx
- src/common/components/media-modal/__stories__/07-footer-product-unavailable.stories.tsx
- media-layout: добавлены примеры по гайдам (patch)
> Шаг 2 #235 MediaLayout: обновить в соответствии с новыми дизайн-гайдами 

- src/common/components/media-modal/__stories__/07-footer-product-unavailable.stories.tsx
- src/common/components/media-modal/parts/product-brief.tsx
- media-modal: добавлена возможность стилизовать картинку в футере (minor)
- media-modal: доработки stories (patch)
>  Шаг 3 #235 MediaLayout: обновить в соответствии с новыми дизайн-гайдами

- package-lock.json
- package.json
- `deps`: обновлен пакет `@sima-land/ui-nucleons` (major)
- `deps`: выполнен `npm audit fix` (patch)
> #236 Badge: обновить в соответствии с новыми дизайн-гайдами

- src/common/components/breadcrumbs/__stories__/01-primary.stories.tsx
- src/common/components/breadcrumbs/breadcrumbs.tsx
- common/breadcrumbs: мелкие правки примеров использования
> Шаг 2 #243 Breadcrumbs: добавить возможность отслуживать события

- package-lock.json
- package.json
- src/common/components/media-gallery/utils.ts
- `deps`: обновлен пакет `@sima-land/ui-nucleons`
Closes #253
> #253 Обновить нуклоны 

- package-lock.json
- package.json
> #253 Обновлены нуклоны

- src/common/components/hover-slider/hover-slider.tsx
- src/common/components/hover-slider/index.ts
- src/common/components/hover-slider/types.ts
- src/common/components/product-info/parts.tsx
- src/common/components/product-info/product-info.tsx
- src/common/components/product-info/types.ts
- hover-slider: мелкие доработки
- product-info: стилистические правки
> Шаг 3 #256 Обновить компонент ProductCard 

- src/common/components/product-info/__test__/product-info.test.tsx
- src/common/components/product-info/index.ts
- src/common/components/product-info/product-info.tsx
- product-info: стилистические правки
> Шаг 4 #256 Обновить компонент ProductCard 

- src/common/components/product-info/__stories__/01-primary.stories.tsx
- src/common/components/product-info/__stories__/02-image-slider.stories.tsx
- src/common/components/product-info/__stories__/03-custom-ratio.stories.tsx
- src/common/components/product-info/__stories__/04-cart-loading.stories.tsx
- src/common/components/product-info/__stories__/05-not-enough.stories.tsx
- src/common/components/product-info/__stories__/06-not-enough-waited.stories.tsx
- src/common/components/product-info/__stories__/07-unavailable.stories.tsx
- src/common/components/product-info/__stories__/08-mature-content.stories.tsx
- src/common/components/product-info/__stories__/09-with-carousel.stories.tsx
- src/common/components/product-info/parts/image.m.scss
- src/common/components/product-info/parts/image.tsx
- src/common/components/rating-counter/__test__/rating-counter.test.tsx
- src/common/components/rating-counter/rating-counter.tsx
- rating-counter: запятая заменена на точку
- product-info: мелкие оптимизации и правки stories
>  Шаг 10 #256 Обновить компонент ProductCard

- src/desktop/components/product-carousel/product-carousel.tsx
- src/desktop/components/product-carousel/types.ts
- ProductCarousel: добавлена возможность отключить бесконечную прокрутку (minor)
Closes #268
> #268 ProductCarousel: добавить возможность задавать infinite 

- src/common/components/product-info/__stories__/05-not-enough.stories.tsx
- src/common/components/product-info/__stories__/06-not-enough-waited.stories.tsx
- src/common/components/product-info/__stories__/08-mature-content.stories.tsx
- src/common/components/product-info/__test__/product-info.test.tsx
- src/common/components/product-info/parts/parts.m.scss
- src/common/components/product-info/parts/prices.tsx
- src/common/components/product-info/parts/rating-counter.m.scss
- src/common/components/product-info/parts/wait-list-added-link.m.scss
- src/common/components/product-info/product-info.tsx
- ProductInfo: обновления в соответствии с новыми дизайн-гайдами (patch)
> #268 Изменить ProductInfo в соответствии с переделанными дизайн-гайдами

- .storybook/webpack.config.js
- package-lock.json
- src/common/components/badge-list/__stories__/index.stories.tsx
- src/common/components/badge/__stories__/badge.stories.tsx
- src/desktop/components/gallery-modal/__stories__/index.stories.tsx
- src/mobile/components/product-slider/__stories__/index.stories.tsx
- src/mobile/components/search-bar/__stories__/index.stories.tsx
- src/mobile/components/select-screen/__stories__/index.stories.tsx
- tsconfig.json
- подготовка к разбиению сторисов на отдельные модули
- добавлены алиасы чтобы скрыть детали реализации документации
> Шаг 1 #272 Отказ от Storybook

- src/mobile/components/person-info/person-info.m.scss
- mobile/product-info: доработки стилей (patch)
> Fix #277 Доработки стилей ProductInfo

- src/common/components/hover-slider/hover-slider.tsx
- src/common/components/hover-slider/types.ts
- src/common/components/product-info/__test__/product-info.test.tsx
- src/common/components/product-info/parts/image.tsx
- src/common/components/product-info/types.ts
- hover-slider: добавлена возможность задавать пропсы навигации (minor)
- product-info: добавлена возможность задавать пропсы слайдера картинок (minor)
- product-info: слайдер картинок теперь не выводится у товаров для взрослых (patch)
> Шаг 1 #279  ProductInfo: доработать в соответствии с новыми дизайн-гайдами

- .github/workflows/gh-pages.yml
- docs/stories/common/components/product-info/01-primary.stories.tsx
- docs/stories/common/components/product-info/02-image-slider.stories.meta.json
- docs/stories/common/components/product-info/02-image-slider.stories.tsx
- docs/stories/common/components/product-info/03-custom-ratio.stories.meta.json
- docs/stories/common/components/product-info/03-custom-ratio.stories.tsx
- docs/stories/common/components/product-info/04-cart-loading.stories.tsx
- docs/stories/common/components/product-info/05-not-enough.stories.tsx
- docs/stories/common/components/product-info/06-not-enough-waited.stories.tsx
- docs/stories/common/components/product-info/07-unavailable.stories.tsx
- docs/stories/common/components/product-info/08-mature-content.stories.tsx
- docs/stories/common/components/product-info/09-with-carousel.stories.tsx
- docs/stories/common/components/product-info/styles.m.css
- docs/stories/desktop/components/product-carousel/01-primary.stories.tsx
- docs/stories/desktop/components/product-carousel/02-unavailable.stories.tsx
- docs/stories/desktop/components/product-carousel/03-adult.stories.tsx
- docs/stories/desktop/components/product-carousel/04-deferred-data.stories.tsx
- docs/stories/desktop/components/product-carousel/05-few-items.stories.tsx
- docs/stories/desktop/components/product-carousel/06-custom-item-size.stories.tsx
- docs/stories/mobile/components/product-slider/01-primary.stories.tsx
- docs/stories/mobile/components/product-slider/02-unavailable.stories.tsx
- docs/stories/mobile/components/product-slider/03-adult.stories.tsx
- src/common/components/product-info/__test__/product-info.test.tsx
- src/common/components/product-info/parts/image.tsx
- src/common/components/product-info/types.ts
- src/desktop/components/product-carousel/__test__/product-carousel.test.tsx
- src/mobile/components/product-slider/__test__/product-slider.test.tsx
- src/mobile/components/product-slider/product-slider.tsx
- product-info: проп src заменен пропом images (major)
- product-slider: добавлен проп itemProps по аналогии с ProductCarousel (minor)
- правки тестов (patch)
- docs: правки примеров использования ProductInfo (patch)
> Шаг 2 #279 ProductInfo: доработать в соответствии с новыми дизайн-гайдами

- docs/package-lock.json
- docs/package.json
- package-lock.json
- package.json
- src/common/components/media-modal/parts/media-view.m.scss
- src/common/components/pagination-controls/pagination-controls.m.scss
- src/desktop/components/gallery-modal/components/gallery-modal.m.scss
- src/mobile/components/action-circles/action-circles.m.scss
- src/mobile/components/action-list/action-list.m.scss
- deps: обновлены пакеты Sass (patch)
- обновлены стили для устранения варнингов sass (patch)
- docs: обновлены пакеты Sass (patch)
Closes #284
> #283 Обновить стили для удаления варнингов Sass 

- docs/stories/common/components/badge/10-gradient.stories.meta.json
- docs/stories/common/components/badge/10-gradient.stories.tsx
- docs/stories/common/components/badge/gradient.m.scss
- package-lock.json
- package.json
- src/common/components/badge/__test__/utils.test.ts
- src/common/components/badge/badge.tsx
- src/common/components/badge/utils.tsx
- badge: теперь умеет выводить градиенты если они заданы через css-переменные (minor)
- deps: обновлен пакет `@sima-land/ui-nucleons` (major)
> Шаг 2 #285 Badge: доработать в соответствии с новыми дизайн-гайдами

- src/desktop/components/product-carousel/product-carousel.tsx
- src/desktop/components/product-carousel/types.ts
- product-carousel: добавлен проп needRequestOptions (minor)
Closes #290
> #290 ProductCarousel: добавить возможность регулировать отступы зоны загрузки 

- docs/stories/common/components/badge-list/02-hints.stories.tsx
- docs/stories/common/components/badge/08-hints-view.stories.tsx
- docs/stories/common/components/badge/09-different-states.stories.tsx
- src/common/components/badge-list/__test__/__snapshots__/badge-list.test.tsx.snap
- src/common/components/badge/__test__/__snapshots__/badge.test.tsx.snap
- src/common/components/badge/__test__/badge.test.tsx
- src/common/components/badge/badge.m.scss
- src/common/components/badge/badge.tsx
- src/common/components/badge/index.ts
- src/common/components/badge/types.ts
- src/mobile/components/product-slider/__test__/__snapshots__/product-slider.test.tsx.snap
- badge: удален проп ref (major)
- badge: проп wothHoverEffect теперь не учитывать наличие href (major)
- badge: добавлен проп rootRef (minor)
- badge: добавлена возможность задавать тег через проп as (minor)
Closes #292
> #292 Badge: добавить возможность менять тег с a на span/div/button

- src/common/components/interactive-image/__test__/__snapshots__/interactive-image.test.tsx.snap
- src/common/components/interactive-image/__test__/interactive-image.test.tsx
- src/common/components/interactive-image/interactive-image.tsx
- Удалена проверка на конкретные дочерние элементы
- Отображено в тестах, проверено локально
> Избавиться от проверки дочерних элементов в интерактивном изображении

- docs/package-lock.json
- docs/stories/common/components/modifier/02-size-m.stories.tsx
- docs/stories/common/components/modifier/03-size-xs.stories.tsx
- package-lock.json
- src/common/components/modifier/__test__/modifier.test.tsx
- src/common/components/modifier/default-border.svg
- src/common/components/modifier/hover-border.svg
- src/common/components/modifier/modifier.m.scss
- src/common/components/modifier/modifier.tsx
- src/common/components/modifier/types.ts
- Modifier: добавлен новый размер модификатора - xs (minor)
- Modifier: добавлена возможность помечать модификатор как несуществующий (minor)
- Modifier: стили компонента приведены в соответствие с макетами (patch)
Макеты: https://www.figma.com/design/QP9m2CcLXBaR0tFhXe2DS9/Web-UI-Kit?node-id=32920-105571&t=BOQMV9uNFX7S85BK-4
> #12142 (#301) Moleculas: Modifier: Обновить компонент

- package-lock.json
- package.json
- src/common/components/hover-slider/__test__/hover-slider.test.tsx
- src/common/components/interactive-image/__test__/interactive-image.test.tsx
- src/desktop/components/breadcrumbs/__test__/breadcrumbs.test.tsx
- src/desktop/components/breadcrumbs/breadcrumbs.tsx
- src/desktop/components/gallery-modal/components/__test__/gallery-modal.test.tsx
- src/desktop/components/gallery-modal/components/__test__/review-info.test.tsx
- src/desktop/components/product-carousel/__test__/product-carousel.test.tsx
- src/mobile/components/product-slider/__test__/product-slider.test.tsx
- src/mobile/components/select-screen/__test__/select-screen.test.tsx
- Исправлены ошибки и предупреждения в тестах
> Исправлены ошибки и предупреждения в тестах #12525
